const zPullRequestParser = async (pull_request) => {

    if (pull_request === undefined) {
        return
    }

    const {
        url: URL,
        id: ID,
        node_id: nodeID,
        html_url: htmlURL,
        diff_url: diffURL,
        patch_url: patchURL,
        issue_url: issueURL,
        number: number,
        state: state,
        locked: locked,
        title: title,
        user: user,
        body: body,
        created_at: createdAt,
        updated_at: updatedAt,
        closed_at: closedAt,
        merged_at: mergedAt,
        merge_commit_sha: mergeCommitSHA,
        assignee: assignee,
        assignees: assignees,
        requested_reviewers: requestedReviewers,
        requested_teams: requestedTeams,
        labels: labels,
        milestone: milestone,
        commits_url: commitsURL,
        review_comments_url: reviewCommentsURL,
        review_comment_url: reviewCommentURL,
        comments_url: commentsURL,
        statuses_url: statusesURL,
        head: head,
        base: base,
        _links: links,
        author_association: authorAssociations,
        merged: merged,
        mergeable: mergeable,
        rebaseable: rebaseable,
        mergeable_state: mergeableState,
        merged_by: mergedBy,
        comments: comments,
        review_comments: reviewComments,
        maintainer_can_modify: maintainerCanModify,
        commits: commits,
        additions: additions,
        deletions: deletions,
        changed_files: changedFiles,
    } = pull_request

    return module.exports = {
        URL,
        ID,
        nodeID,
        htmlURL,
        diffURL,
        patchURL,
        issueURL,
        number,
        state,
        locked,
        title,
        user,
        body,
        createdAt,
        updatedAt,
        closedAt,
        mergedAt,
        mergeCommitSHA,
        assignee,
        assignees,
        requestedReviewers,
        requestedTeams,
        labels,
        milestone,
        commitsURL,
        reviewCommentsURL,
        reviewCommentURL,
        commentsURL,
        statusesURL,
        head,
        base,
        links,
        authorAssociations,
        merged,
        mergeable,
        rebaseable,
        mergeableState,
        mergedBy,
        comments,
        reviewComments,
        maintainerCanModify,
        commits,
        additions,
        deletions,
        changedFiles,
    }
}

module.exports = {
    zPullRequestParser,
}