module.exports = `{{#if body}}
{{ body }}

---

{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ filename }}#{{ range }}

---

{{/if}}

###### This issue was generated by @zeobot based on a \`{{ keyword }}\` tag in comment in {{ sha }}.
{{#if mentions}}
###### {{ mentions }} were detect as mentioned based on a \`@todo-zeobot(a)\` tag in comment
{{/if}}
###### It's been automatically assigned to @{{ author }} because they committed the code
{{#if assignees}}
###### Only {{ assignees }} assigned to this issue because they are contributors for this repository
{{/if}}`
