module.exports = `## {{ title }}

{{#if body}}
{{ body }}

---

{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ filename }}#{{ range }}

---

{{/if}}
###### This comment was generated by @zeobot based on a \`{{ keyword }}\` tag in comment in {{ sha }}
###### An issue (#{{ number }}) was opened for this task.
###### Task author: {{ assignedToString }}`
