module.exports = `{{#if body}}
{{ body }}

---

{{/if}}
{{#if range}}
https://{{ githubHost }}/{{ owner }}/{{ repo }}/blob/{{ sha }}/{{ filename }}#{{ range }}

---

{{/if}}
###### This issue was generated by [zeobot](https://github.com/zeoflow/zeobot) based on a \`{{ keyword }}\` comment in {{ sha }} when #{{ number }} was merged.{{ assignedToString }}`
