const zRepositoryParser = async (repository) => {

    if (repository === undefined) {
        return
    }

    const {
        id: repositoryID,
        node_id: repositoryNodeID,
        name: repositoryName,
        full_name: repositoryFullName,
        owner: repositoryOwner,
        private: repositoryPrivate,
        html_url: repositoryHtmlURL,
        description: repositoryDescription,
        fork: repositoryFork,
        url: repositoryURL,
        forks_url: repositoryForksURL,
        keys_url: repositoryKeysURL,
        collaborators_url: repositoryCollaboratorsURL,
        teams_url: repositoryTeamsURL,
        hooks_url: repositoryHooksURL,
        issue_events_url: repositoryIssueEventsURL,
        events_url: repositoryEventsURL,
        assignees_url: repositoryAssigneesURL,
        branches_url: repositoryBranchesURL,
        tags_url: repositoryTagsURL,
        blobs_url: repositoryBlobsURL,
        git_tags_url: repositoryGitTagsURL,
        git_refs_url: repositoryGitRefsURL,
        trees_url: repositoryTreesURL,
        statuses_url: repositoryStatusesURL,
        languages_url: repositoryLanguagesURL,
        stargazers_url: repositoryStargazersURL,
        contributors_url: repositoryContributorsURL,
        subscribers_url: repositorySubscribersURL,
        subscription_url: repositorySubscriptionURL,
        commits_url: repositoryCommitsURL,
        git_commits_url: repositoryGitCommitsURL,
        comments_url: repositoryCommentsURL,
        issue_comment_url: repositoryIssueCommentURL,
        contents_url: repositoryContentsURL,
        compare_url: repositoryCompareURL,
        merges_url: repositoryMergesURL,
        archive_url: repositoryArchiveURL,
        downloads_url: repositoryDownloadsURL,
        issues_url: repositoryIssuesURL,
        pulls_url: repositoryPullsURL,
        milestones_url: repositoryMilestonesURL,
        notifications_url: repositoryNotificationsURL,
        labels_url: repositoryLabelsURL,
        releases_url: repositoryReleasesURL,
        deployments_url: repositoryDeploymentsURL,
        created_at: repositoryCreatedAt,
        updated_at: repositoryUpdatedAt,
        pushed_at: repositoryPushedAt,
        git_url: repositoryGitURL,
        ssh_url: repositorySshURL,
        clone_url: repositoryCloneURL,
        svn_url: repositorySvnURL,
        homepage: repositoryHomepage,
        size: repositorySize,
        stargazers_count: repositoryStargazersCount,
        watchers_count: repositoryWatchersCount,
        language: repositoryLanguage,
        has_issues: repositoryHasIssues,
        has_projects: repositoryHasProjects,
        has_downloads: repositoryHasDownloads,
        has_wiki: repositoryHasWiki,
        has_pages: repositoryHasPages,
        forks_count: repositoryForkesCount,
        mirror_url: repositoryMirrorURL,
        archived: repositoryArchived,
        open_issues_count: repositoryOpenIssuesCount,
        license: repositoryLicense,
        forks: repositoryForks,
        open_issues: repositoryOpenIssues,
        watchers: repositoryWatchers,
        default_branch: repositoryDefaultBranch,
        stargazers: repositoryStargazers,
        master_branch: repositoryMasterBranch,
        permissions: repositoryPermissions,
    } = repository
    const repositoryOwnerUsername = repositoryOwner.login

    return module.exports = {
        repositoryID,
        repositoryNodeID,
        repositoryName,
        repositoryFullName,
        repositoryOwner,
        repositoryOwnerUsername,
        repositoryPrivate,
        repositoryHtmlURL,
        repositoryDescription,
        repositoryFork,
        repositoryURL,
        repositoryForksURL,
        repositoryKeysURL,
        repositoryCollaboratorsURL,
        repositoryTeamsURL,
        repositoryHooksURL,
        repositoryIssueEventsURL,
        repositoryEventsURL,
        repositoryAssigneesURL,
        repositoryBranchesURL,
        repositoryTagsURL,
        repositoryBlobsURL,
        repositoryGitTagsURL,
        repositoryGitRefsURL,
        repositoryTreesURL,
        repositoryStatusesURL,
        repositoryLanguagesURL,
        repositoryStargazersURL,
        repositoryContributorsURL,
        repositorySubscribersURL,
        repositorySubscriptionURL,
        repositoryCommitsURL,
        repositoryGitCommitsURL,
        repositoryCommentsURL,
        repositoryIssueCommentURL,
        repositoryContentsURL,
        repositoryCompareURL,
        repositoryMergesURL,
        repositoryArchiveURL,
        repositoryDownloadsURL,
        repositoryIssuesURL,
        repositoryPullsURL,
        repositoryMilestonesURL,
        repositoryNotificationsURL,
        repositoryLabelsURL,
        repositoryReleasesURL,
        repositoryDeploymentsURL,
        repositoryCreatedAt,
        repositoryUpdatedAt,
        repositoryPushedAt,
        repositoryGitURL,
        repositorySshURL,
        repositoryCloneURL,
        repositorySvnURL,
        repositoryHomepage,
        repositorySize,
        repositoryStargazersCount,
        repositoryWatchersCount,
        repositoryLanguage,
        repositoryHasIssues,
        repositoryHasProjects,
        repositoryHasDownloads,
        repositoryHasWiki,
        repositoryHasPages,
        repositoryForkesCount,
        repositoryMirrorURL,
        repositoryArchived,
        repositoryOpenIssuesCount,
        repositoryLicense,
        repositoryForks,
        repositoryOpenIssues,
        repositoryWatchers,
        repositoryDefaultBranch,
        repositoryStargazers,
        repositoryMasterBranch,
        repositoryPermissions,
    }

}

module.exports = {
    zRepositoryParser,
}